-- Supabase SQL Editor에서 한 번 실행하면 공유 리더보드/방명록이 활성화됩니다.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id text not null,
  user_name text not null,
  game text not null check (game in ('yahtzee','seven','cantstop')),
  score integer not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  user_id text not null,
  user_name text not null,
  message text not null check (char_length(message) <= 500),
  created_at timestamptz not null default now()
);
alter table public.scores enable row level security;
alter table public.guestbook enable row level security;
drop policy if exists "public read scores" on public.scores;
drop policy if exists "public insert scores" on public.scores;
drop policy if exists "public read guestbook" on public.guestbook;
drop policy if exists "public insert guestbook" on public.guestbook;
create policy "public read scores" on public.scores for select to anon using (true);
create policy "public insert scores" on public.scores for insert to anon with check (true);
create policy "public read guestbook" on public.guestbook for select to anon using (true);
create policy "public insert guestbook" on public.guestbook for insert to anon with check (char_length(message) <= 500);
create index if not exists scores_game_score_idx on public.scores(game, score desc);
create index if not exists guestbook_created_idx on public.guestbook(created_at desc);
