-- 보겜동 비동기 TRPG용 테이블. Supabase SQL Editor에서 한 번만 실행하세요.

create table if not exists public.trpg_campaigns (
  id text primary key,
  scenario_id text not null,
  title text not null,
  status text not null default 'active' check (status in ('active','ended')),
  current_scene text not null,
  state jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.trpg_players (
  campaign_id text not null references public.trpg_campaigns(id) on delete cascade,
  user_id text not null,
  user_name text not null,
  assigned_number integer not null check (assigned_number between 1 and 5),
  hp integer not null default 10,
  stamina integer not null default 10,
  stamina_date text not null,
  items jsonb not null default '[]'::jsonb,
  primary key (campaign_id,user_id)
);

create table if not exists public.trpg_logs (
  id bigint generated by default as identity primary key,
  campaign_id text not null references public.trpg_campaigns(id) on delete cascade,
  user_id text,
  user_name text,
  kind text not null default 'action',
  message text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.trpg_votes (
  campaign_id text not null references public.trpg_campaigns(id) on delete cascade,
  scene_id text not null,
  vote_id text not null,
  user_id text not null,
  user_name text not null,
  choice_id text not null,
  updated_at timestamptz not null default now(),
  primary key (campaign_id,scene_id,vote_id,user_id)
);

create table if not exists public.trpg_memo (
  campaign_id text primary key references public.trpg_campaigns(id) on delete cascade,
  content text not null default '' check (char_length(content) <= 4000),
  updated_by text,
  updated_name text,
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

alter table public.trpg_campaigns enable row level security;
alter table public.trpg_players enable row level security;
alter table public.trpg_logs enable row level security;
alter table public.trpg_votes enable row level security;
alter table public.trpg_memo enable row level security;

do $$
begin
  execute 'drop policy if exists "trpg campaigns read" on public.trpg_campaigns';
  execute 'drop policy if exists "trpg campaigns insert" on public.trpg_campaigns';
  execute 'drop policy if exists "trpg campaigns update" on public.trpg_campaigns';
  execute 'drop policy if exists "trpg players read" on public.trpg_players';
  execute 'drop policy if exists "trpg players insert" on public.trpg_players';
  execute 'drop policy if exists "trpg players update" on public.trpg_players';
  execute 'drop policy if exists "trpg logs read" on public.trpg_logs';
  execute 'drop policy if exists "trpg logs insert" on public.trpg_logs';
  execute 'drop policy if exists "trpg votes read" on public.trpg_votes';
  execute 'drop policy if exists "trpg votes insert" on public.trpg_votes';
  execute 'drop policy if exists "trpg votes update" on public.trpg_votes';
  execute 'drop policy if exists "trpg memo read" on public.trpg_memo';
  execute 'drop policy if exists "trpg memo insert" on public.trpg_memo';
  execute 'drop policy if exists "trpg memo update" on public.trpg_memo';
end $$;

create policy "trpg campaigns read" on public.trpg_campaigns for select to anon using (true);
create policy "trpg campaigns insert" on public.trpg_campaigns for insert to anon with check (true);
create policy "trpg campaigns update" on public.trpg_campaigns for update to anon using (true) with check (true);
create policy "trpg players read" on public.trpg_players for select to anon using (true);
create policy "trpg players insert" on public.trpg_players for insert to anon with check (true);
create policy "trpg players update" on public.trpg_players for update to anon using (true) with check (true);
create policy "trpg logs read" on public.trpg_logs for select to anon using (true);
create policy "trpg logs insert" on public.trpg_logs for insert to anon with check (char_length(message) <= 2000);
create policy "trpg votes read" on public.trpg_votes for select to anon using (true);
create policy "trpg votes insert" on public.trpg_votes for insert to anon with check (true);
create policy "trpg votes update" on public.trpg_votes for update to anon using (true) with check (true);
create policy "trpg memo read" on public.trpg_memo for select to anon using (true);
create policy "trpg memo insert" on public.trpg_memo for insert to anon with check (char_length(content) <= 4000);
create policy "trpg memo update" on public.trpg_memo for update to anon using (true) with check (char_length(content) <= 4000);

create index if not exists trpg_logs_campaign_created_idx on public.trpg_logs(campaign_id,created_at desc);
create index if not exists trpg_votes_campaign_scene_idx on public.trpg_votes(campaign_id,scene_id,vote_id);

insert into public.trpg_campaigns(id,scenario_id,title,status,current_scene,state,version)
values(
  'haunted-house-1',
  'haunted-house',
  '무언가 나오는 폐가',
  'active',
  'internet',
  '{"flags":{},"clues":[],"escapeProgress":0,"ending":null}'::jsonb,
  1
)
on conflict (id) do nothing;

insert into public.trpg_players(campaign_id,user_id,user_name,assigned_number,hp,stamina,stamina_date,items)
values
  ('haunted-house-1','hyunsu','차현수',1,10,10,(now() at time zone 'Asia/Seoul')::date::text,'[]'::jsonb),
  ('haunted-house-1','sieun','연시은',2,10,10,(now() at time zone 'Asia/Seoul')::date::text,'[]'::jsonb),
  ('haunted-house-1','sugang','한수강',3,10,10,(now() at time zone 'Asia/Seoul')::date::text,'[]'::jsonb),
  ('haunted-house-1','somi','김소미',4,10,10,(now() at time zone 'Asia/Seoul')::date::text,'[]'::jsonb),
  ('haunted-house-1','host','김준희',5,10,10,(now() at time zone 'Asia/Seoul')::date::text,'[]'::jsonb)
on conflict (campaign_id,user_id) do nothing;

insert into public.trpg_memo(campaign_id,content,version)
values('haunted-house-1','',1)
on conflict (campaign_id) do nothing;
